download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",destfile = "UCdata",method = "curl")
unzip("UCdata")
UC.data = read.table("household_power_consumption.txt",sep = ";",header = T,stringsAsFactors = F)
UC.data[,1] = as.Date(UC.data[,1],format = "%d/%m/%Y")
UCF = subset(UC.data, UC.data[,1] == "2007-02-01"|UC.data[,1] == "2007-02-02")
UCF[,"Global_active_power"] = as.numeric(UCF[,"Global_active_power"])

png(filename = "plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
plot(UCF[,"Global_active_power"],type = "s",xlab = "",ylab = "Global Active Power (kilowatts)",xaxt = "n")
axis(side = 1, at = c(0,1440,2880),labels = c("Thu","Fri","Sat"))
plot(UCF[,"Voltage"],type = "s",xlab = "datetime",ylab = "Voltage",xaxt = 'n')
axis(side = 1, at = c(0,1440,2880),labels = c("Thu","Fri","Sat"))
plot(UCF[,"Sub_metering_1"],type = "s",xlab = "",ylab = "Global Active Power (kilowatts)",xaxt = "n")
axis(side = 1, at = c(0,1440,2880),labels = c("Thu","Fri","Sat"))
lines(UCF[,"Sub_metering_3"],col = "blue")
lines(UCF[,"Sub_metering_2"],col = "red")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1,col = c("black","blue","red"),bty = "n")
plot(UCF[,"Global_reactive_power"],type = "s",xlab = "datetime",ylab = "Global_reactive_power",xaxt = 'n')
axis(side = 1, at = c(0,1440,2880),labels = c("Thu","Fri","Sat"))

dev.off()
